# Hydro Agent Configuration
# This file contains the configuration for the sample agent

# Agent identification
agent_code=OUTFLOW_PLAN_AGENT_POWER
agent_type=OUTFLOW_PLAN_AGENT
agent_name=水电站出力规划智能体


# Agent meta
version=0.0.1
description=水电站出力规划智能体


# Agent drive mode (SIM_TICK_DRIVEN, EVENT_DRIVEN, PROACTIVE)
drive_mode=SIM_TICK_DRIVEN

# HydroSim MPC integration
# 请按实际部署路径配置以下 4 个文件
# hydrosim_time_series_file=F:\\sl\\hydros\\hydros-python-sdk\\custom-agent\\power\\mpc\\time_series_base.json
# hydrosim_mpc_config_file=F:\\sl\\hydros\\hydros-python-sdk\\custom-agent\\power\\mpc\\mpc_config.yaml
# hydrosim_initial_states_file=F:\\sl\\hydros\\hydros-python-sdk\\custom-agent\\power\\mpc\\initial_states.yaml
# hydrosim_constraints_file=F:\\sl\\hydros\\hydros-python-sdk\\custom-agent\\power\\mpc\\constrains_targets.yaml

