class AgentEventType:
    """与 Java AgentEventType code 对齐的 Hydros Agent event_type 常量。"""

    WEATHER_FORECAST = "WEATHER_FORECAST"
    WATER_USE = "WATER_USE"
    PUMP_STATION_POWER_OUTAGE = "PUMP_STATION_POWER_OUTAGE"
    DEVICE_FAULT = "DEVICE_FAULT"
    NOISE_SIMULATION = "NOISE_SIMULATION"
    OUTFLOW_TIME_SERIES = "OUTFLOW_TIME_SERIES"
    DEVICE_STATUS_CHANGE = "DEVICE_STATUS_CHANGE"

    HYDRO_ALERT = "HYDRO_ALERT"
    HYDRO_MONITOR_RULE = "HYDRO_MONITOR_RULE"
    TIME_SERIES_DATA_UPDATED = "TIME_SERIES_DATA_UPDATED"
    OUTFLOW_TIME_SERIES_DATA_UPDATED = "OUTFLOW_TIME_SERIES_DATA_UPDATED"

    STEP_TICK = "STEP_TICK"
