apiVersion: v1
kind: Service
metadata:
  name: hydros-control-algorithms
  namespace: ${KUBE_NAMESPACE}
spec:
  selector:
    app: hydros-control-algorithms
  ports:
    - name: http
      port: 8015
      targetPort: http
